@echo off
echo Starting Backend Server...
cd "c:\Users\Ayush Tripathi\Documents\GitHub\Major\backend"
echo Installing dependencies...
call npm install
echo Starting server...
call npm run server
pause